# Generated by Django 2.2.15 on 2023-09-13 04:28

from django.db import migrations, models
from consumption.helpers import generate_random_token

def set_default_tokens(apps, schema_editor):
    User = apps.get_model('consumption', 'User')
    for user in User.objects.all():
        if not user.token:
            user.token = generate_random_token()
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_auto_20230911_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.RunPython(set_default_tokens),
    ]
