# Generated by Django 2.2.15 on 2023-09-13 04:35

import consumption.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=consumption.helpers.generate_random_token, max_length=32, unique=True),
        ),
    ]
